#!/usr/bin/env bash
# Temporarily suppress root's X11 startup path inside a running browser-QEMU
# A/UX guest, using auxagent over the Dialtone Ethernet zone.
#
# Normal browser-QEMU launches use QEMU -snapshot, so these guest-side edits are
# lost on reload. If you intentionally run through disk-relay/writable disks,
# use `restore` before promoting the disk.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZONE="${1:-codex-classic}"
MODE="${2:-apply}"
AUXCTL=(node "${ROOT}/scripts/auxctl-zone.mjs" --zone "${ZONE}")

case "${MODE}" in
  apply|restore) ;;
  *)
    echo "usage: $0 [zone] [apply|restore]" >&2
    exit 2
    ;;
esac

wait_for_auxagent() {
  echo "waiting for auxagent in zone=${ZONE}..."
  for _ in $(seq 1 36); do
    if "${AUXCTL[@]}" ping 2>/dev/null | grep -q auxagent; then
      echo "auxagent up."
      return 0
    fi
    sleep 5
  done
  echo "auxagent never answered; boot with NET=1 NET_ZONE=${ZONE} first." >&2
  return 1
}

wait_for_auxagent

if [ "${MODE}" = "restore" ]; then
  REMOTE="$(cat <<'REMOTE'
set -e
echo "browser-qemu classic-only mode: restoring X startup files"
for f in /.bash_profile /.profile /.login /.cshrc /.x11start
do
  if [ -f "$f.browser-qemu-x11" ]; then
    cp "$f.browser-qemu-x11" "$f"
    echo "restored $f"
  fi
done
sync
echo "restore complete"
REMOTE
)"
else
  REMOTE="$(cat <<'REMOTE'
set -e
echo "browser-qemu classic-only mode: backing up root startup files"
for f in /.bash_profile /.profile /.login /.cshrc /.x11start
do
  if [ -f "$f" ] && [ ! -f "$f.browser-qemu-x11" ]; then
    cp "$f" "$f.browser-qemu-x11"
    echo "backed up $f"
  fi
done

cat > /.bash_profile <<'EOF'
# browser-qemu classic-only snapshot profile.
# Generated by scripts/aux-classic-mode.sh.
PATH=/usr/local/bin:/usr/local/gnu/bin:/bin:/usr/bin:/usr/ucb:/mac/bin:/etc:/usr/etc
SHELL=/bin/bash
export PATH
export SHELL
echo "browser-qemu classic-only mode: X startup suppressed for this snapshot."
echo "Restore with: make aux-classic-restore ZONE=<zone>"
EOF

cat > /.login <<'EOF'
echo "browser-qemu classic-only mode: X startup suppressed for this snapshot."
EOF

cat > /.cshrc <<'EOF'
set path=(/usr/local/bin /usr/local/gnu/bin /bin /usr/bin /usr/ucb /mac/bin /etc /usr/etc)
echo "browser-qemu classic-only mode: X startup suppressed for this snapshot."
EOF

cat > /.x11start <<'EOF'
#!/bin/sh
echo "browser-qemu classic-only mode: refusing X startup in this snapshot."
exit 0
EOF
chmod 755 /.x11start

sync
echo "classic-only profile installed"
REMOTE
)"
fi

"${AUXCTL[@]}" exec "${REMOTE}"
